apiVersion: mariadb.mmontes.io/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
spec:
  image: mariadb/maxscale:23.08
  imagePullPolicy: IfNotPresent

  servers:
    - name: mariadb-0
      address: mariadb-repl-0.mariadb-repl-internal.default.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend
    - name: mariadb-1
      address: mariadb-repl-1.mariadb-repl-internal.default.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend
    - name: mariadb-2
      address: mariadb-repl-2.mariadb-repl-internal.default.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend

  admin:
    port: 8989
    username: mariadb-operator
    passwordSecretKeyRef:
      name: maxscale-admin
      key: password
    deleteDefaultAdmin: true
    guiEnabled: true

  config:
    params:
      log_info: "true"
    volumeClaimTemplate:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false

  updateStrategy:
    type: RollingUpdate

  replicas: 3

  kubernetesService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.210

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - maxscale
          topologyKey: "kubernetes.io/hostname"

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 66%
