apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce

  replicas: 3

  # point to an existing MaxScale instance. Doing this will delegate tasks such as primary failover to MaxScale.
  # maxScaleRef:
  #   name: maxscale

  # provision a MaxScale instance and set 'spec.maxScaleRef' automatically.
  maxScale:
    enabled: true

    kubernetesService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.219

  replication:
    enabled: true

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.120

  primaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.130

  secondaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.131

  metrics:
    enabled: true