apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce

  replicas: 3

  maxScale:
    enabled: true
    services:
      - name: rw-router
        router: readwritesplit
        params:
          transaction_replay: "true"
          transaction_replay_attempts: "10"
          transaction_replay_timeout: "5s"
          max_slave_connections: "255"
          max_replication_lag: "3s"
          master_accept_reads: "true"
        listener:
          port: 3306
          protocol: MariaDBProtocol
          params:
            connection_metadata: "tx_isolation=auto"
      - name: rconn-master-router
        router: readconnroute
        params:
          router_options: "master"
          max_replication_lag: "3s"
          master_accept_reads: "true"
        listener:
          port: 3307
      - name: rconn-slave-router
        router: readconnroute
        params:
          router_options: "slave"
          max_replication_lag: "3s"
        listener:
          port: 3308

    monitor:
      interval: 2s
      cooperativeMonitoring: majority_of_all
      params:
        auto_failover: "true"
        auto_rejoin: "true"
        switchover_on_low_disk_space: "true"

    kubernetesService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.216

  replication:
    enabled: true

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.120

  primaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.130

  secondaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.131

  metrics:
    enabled: true