apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce

  replicas: 3

  maxScaleRef:
    name: maxscale

  replication:
    enabled: true

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.120

  primaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.130

  secondaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.131

  metrics:
    enabled: true

  livenessProbe:
    exec:
      command:
        - bash
        - -c
        - |
          if [[ $(mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SHOW VARIABLES LIKE 'rpl_semi_sync_slave_enabled';" --skip-column-names | grep -c "ON") -eq 1 ]]; then
            mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SHOW SLAVE 'mariadb-operator' STATUS\G" | grep -c "Slave_IO_Running: Yes" 
          else
            mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" -e "SELECT 1;"
          fi