apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-from-nfs
spec:
  storage:
    size: 1Gi

  bootstrapFrom:
    volume:
      nfs:
        server: nas.local
        path: /volume1/mariadb
    targetRecoveryTime: 2023-12-19T09:00:00Z
