apiVersion: mariadb.mmontes.io/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
spec:
  servers:
    - name: mariadb-0
      address: mariadb-repl-0.mariadb-repl-internal.default.svc.cluster.local
    - name: mariadb-1
      address: mariadb-repl-1.mariadb-repl-internal.default.svc.cluster.local
    - name: mariadb-2
      address: mariadb-repl-2.mariadb-repl-internal.default.svc.cluster.local

  monitor:
    module: mariadbmon
    interval: 2s
    cooperativeMonitoring: majority_of_all
    params:
      auto_failover: "true"
      auto_rejoin: "true"
      switchover_on_low_disk_space: "true"   

  # TODO: create User and Grants in the operator
  auth:
    clientUsername: maxscale-client
    clientPasswordSecretKeyRef:
      name: mariadb
      key: password
    serverUsername: maxscale-server
    serverPasswordSecretKeyRef:
      name: mariadb
      key: password
    monitorUsername: maxscale-monitor
    monitorPasswordSecretKeyRef:
      name: mariadb
      key: password

  kubernetesService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.210
