apiVersion: mariadb.mmontes.io/v1alpha1
kind: MaxScale
metadata:
  name: maxscale
spec:
  image: mariadb/maxscale:23.08
  imagePullPolicy: IfNotPresent

  servers:
    - name: mariadb-0
      address: mariadb-repl-0.mariadb-repl-internal.default.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend
    - name: mariadb-1
      address: mariadb-repl-1.mariadb-repl-internal.default.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend
    - name: mariadb-2
      address: mariadb-repl-2.mariadb-repl-internal.default.svc.cluster.local
      port: 3306
      protocol: MariaDBBackend

  services:
    - name: rw-router
      router: readwritesplit
      params:
        transaction_replay: "true"
        transaction_replay_attempts: "10"
        transaction_replay_timeout: "5s"
        max_slave_connections: "255"
        max_replication_lag: "3s"
        master_accept_reads: "true"
    - name: rconn-master-router
      router: readconnroute
      params:
        router_options: "master"
        max_replication_lag: "3s"
        master_accept_reads: "true"
    - name: rconn-slave-router
      router: readconnroute
      params:
        router_options: "slave"
        max_replication_lag: "3s"

  monitor:
    module: mariadbmon
    interval: 2s
    cooperativeMonitoring: majority_of_all
    params:
      auto_failover: "true"
      auto_rejoin: "true"
      switchover_on_low_disk_space: "true"

  admin:
    port: 8989
    username: mariadb-operator
    passwordSecretKeyRef:
      name: maxscale-admin
      key: password
    deleteDefaultAdmin: true
    guiEnabled: true

  config:
    params:
      log_info: "true"
    volumeClaimTemplate:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce

  # TODO: create User and Grants in the operator
  auth:
    clientUsername: maxscale-client
    clientPasswordSecretKeyRef:
      name: mariadb
      key: password
    serverUsername: maxscale-server
    serverPasswordSecretKeyRef:
      name: mariadb
      key: password
    monitorUsername: maxscale-monitor
    monitorPasswordSecretKeyRef:
      name: mariadb
      key: password

  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false

  updateStrategy:
    type: RollingUpdate

  replicas: 3

  kubernetesService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.210

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - maxscale
          topologyKey: "kubernetes.io/hostname"

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 66%
