apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  username: mariadb
  database: mariadb

  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
    accessModes:
      - ReadWriteOnce

  replicas: 3

  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: false
    sst: mariabackup
    replicaThreads: 1
    agent:
      image: ghcr.io/mariadb-operator/agent:v0.0.3
      port: 5555
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 5s
    recovery:
      enabled: true
      clusterHealthyTimeout: 3m
      clusterBootstrapTimeout: 10m
      podRecoveryTimeout: 5m
      podSyncTimeout: 5m
    initContainer:
      image: ghcr.io/mariadb-operator/init:v0.0.13
    volumeClaimTemplate:
      resources:
        requests:
          storage: 300Mi
      accessModes:
        - ReadWriteOnce

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.150
  connection:
    secretName: mariadb-galera-conn
    secretTemplate:
      key: dsn

  primaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.160
  primaryConnection:
    secretName: mariadb-galera-conn-primary
    secretTemplate:
      key: dsn

  secondaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.161
  secondaryConnection:
    secretName: mariadb-galera-conn-secondary
    secretTemplate:
      key: dsn

  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       - labelSelector:
  #           matchExpressions:
  #             - key: app.kubernetes.io/instance
  #               operator: In
  #               values:
  #                 - mariadb-galera
  #         topologyKey: "kubernetes.io/hostname"

  # tolerations:
  #   - key: "mariadb.mmontes.io/ha"
  #     operator: "Exists"
  #     effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 33%

  updateStrategy:
    type: RollingUpdate

  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      memory: 1Gi

  metrics:
    enabled: true

  maxScale:
    enabled: true

    kubernetesService:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 172.18.0.229