apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: maxscale-client-galera
spec:
  mariaDbRef:
    name: mariadb-galera
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
  database: "*"
  table: "*"
  username: maxscale-client
  grantOption: false
  host: "%" 
  retryInterval: 5s