apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: maxscale-client-galera
spec:
  name: maxscale-client
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: maxscale
    key: password
  maxUserConnections: 20
  host: "%" 
  retryInterval: 5s