apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-0-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.70
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mxs-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mxs-galera-0
  publishNotReadyAddresses: true
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-1-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.71
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mxs-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mxs-galera-1
  publishNotReadyAddresses: true
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-2-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.72
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mxs-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mxs-galera-2
  publishNotReadyAddresses: true
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-3-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.73
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mxs-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mxs-galera-3
  publishNotReadyAddresses: true
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-maxscale-0-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.80
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mxs-galera-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mxs-galera-maxscale-0  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-maxscale-1-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.81
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mxs-galera-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mxs-galera-maxscale-1 
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-maxscale-2-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.82
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mxs-galera-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mxs-galera-maxscale-2
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mxs-galera-maxscale-3-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.83
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mxs-galera-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mxs-galera-maxscale-3
  type: LoadBalancer