apiVersion: batch/v1
kind: CronJob
metadata:
  name: sysbench-repl
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: sysbench
            image: severalnines/sysbench
            command:
              - sysbench 
              - oltp_read_write 
              - --tables=10 
              - --table_size=1000000
              - --mysql-host=mariadb-repl-maxscale.default.svc.cluster.local
              - --mysql-port=3306
              - --mysql-user=mariadb-repl-maxscale-client
              - --mysql-password=HkB(0tFe~85y4oQW
              - --mysql-db=sbtest
              - --time=300 
              - --threads=16 
              - --report-interval=1
              - run
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 300m
                memory: 512Mi